services:
  kafka1:
    image: apache/kafka:${KAFKA_VERSION}
    environment:
      CLUSTER_ID: ${CLUSTER_ID}
      KAFKA_NODE_ID: "1"
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka1:9092,EXTERNAL://localhost:19092,PROXY://localhost:19093
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENERS: CONTROLLER://0.0.0.0:9093,INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:19092,PROXY://0.0.0.0:19093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,PROXY:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: "1"
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: "1"
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka1:9093
      KAFKA_PROCESS_ROLES: broker,controller
      JAVA_TOOL_OPTIONS: ${JAVA_TOOL_OPTIONS}
    restart: on-failure
    ports:
      - "19092:19092"
    healthcheck:
      test: /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka1:9092 --list > /dev/null 2>&1
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s
  nginx:
    image: kafka-nginx
    build: ./nginx
    depends_on:
      - kafka1
    cap_add:
      - NET_ADMIN
    volumes:
      - ./nginx/single_kafka_node_nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "19093:19093"